import py_compile
import tempfile
import unittest
from pathlib import Path

from scripts.build_molab import build_artifact


class BuildMolabTest(unittest.TestCase):
    def test_build_artifact_creates_single_compileable_file(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            output = Path(temp_dir) / "foresight_molab.py"
            build_artifact(output)
            source = output.read_text(encoding="utf-8")

            self.assertIn("Generated by scripts/build_molab.py", source)
            self.assertLess(
                source.index("app = marimo.App"),
                source.index("# ---- BEGIN inlined project modules ----"),
            )
            self.assertIn("sample_beancount =", source)
            self.assertIn("anywidget", source)
            self.assertNotIn("from modules.", source)
            self.assertNotIn("from common.", source)
            py_compile.compile(str(output), doraise=True)
