from __future__ import annotations

import argparse
from pathlib import Path
import textwrap


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "dist" / "foresight_molab.py"
SAMPLE_LEDGER = ROOT / "examples" / "sample.beancount"

DEPENDENCIES = [
    "anywidget",
    "beancount",
    "beanquery",
    "marimo",
    "polars",
    "python-dateutil",
    "traitlets",
]

INLINE_FILES = [
    "common/libbeanmarimo.py",
    "common/shared.py",
    "modules/expenses/analysis.py",
    "modules/expenses/index.py",
    "modules/estate/ownership.py",
    "modules/estate/beneficiaries.py",
    "modules/estate/index.py",
    "modules/investments/account_types.py",
    "modules/investments/asset_allocation.py",
    "modules/investments/cash_drag.py",
    "modules/investments/growth.py",
    "modules/investments/index.py",
    "modules/retirement/contributions.py",
    "modules/retirement/index.py",
    "modules/taxes/gains_minimizer.py",
    "modules/taxes/index.py",
]

INTERNAL_IMPORT_PREFIXES = (
    "from common.",
    "from modules.",
)


def build_artifact(output: Path = DEFAULT_OUTPUT) -> Path:
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    source = "\n\n".join(
        [
            build_header(),
            build_inline_sources(),
            build_app_source(),
        ]
    )
    output.write_text(source, encoding="utf-8")
    return output


def build_header() -> str:
    dependency_lines = "\n".join(f'#   "{dependency}",' for dependency in DEPENDENCIES)
    return f'''# /// script
# dependencies = [
{dependency_lines}
# ]
# ///
#
# Generated by scripts/build_molab.py. Do not edit by hand.
# Run with:
#   marimo run foresight_molab.py
# If BEANCOUNT_FILE is not set, this file writes and uses the bundled sample ledger.
'''


def build_inline_sources() -> str:
    parts = []
    for relative_path in INLINE_FILES:
        path = ROOT / relative_path
        parts.append(
            f"# ---- BEGIN {relative_path} ----\n"
            f"{strip_relative_imports(path.read_text(encoding='utf-8')).rstrip()}\n"
            f"# ---- END {relative_path} ----"
        )
    return "\n\n".join(parts)


def strip_relative_imports(source: str) -> str:
    return "\n".join(
        line for line in source.splitlines() if not line.startswith("from .")
    )


def build_app_source() -> str:
    source = (ROOT / "app.py").read_text(encoding="utf-8")
    source = strip_internal_import_blocks(source)
    source = add_sample_ledger_fallback(source)
    return "# ---- BEGIN app.py ----\n" + source.rstrip() + "\n# ---- END app.py ----\n"


def strip_internal_import_blocks(source: str) -> str:
    lines = source.splitlines()
    stripped = []
    skip_block = False

    for line in lines:
        stripped_line = line.lstrip()
        if skip_block:
            if stripped_line == ")":
                skip_block = False
            continue

        if stripped_line.startswith(INTERNAL_IMPORT_PREFIXES):
            if stripped_line.endswith("("):
                skip_block = True
            continue

        stripped.append(line)

    return "\n".join(stripped)


def add_sample_ledger_fallback(source: str) -> str:
    sample = SAMPLE_LEDGER.read_text(encoding="utf-8")
    original = '''    import os

    liability_community_property = "Community Prop"
    beancount_file = os.environ.get("BEANCOUNT_FILE", "").strip()
    if not beancount_file:
        beancount_error = "Environment variable `$BEANCOUNT_FILE` not set."
    elif not os.path.exists(beancount_file):
        beancount_error = f"File not found: `{beancount_file}`"
    else:
        beancount_error = ""'''
    replacement = f'''    import os
    from pathlib import Path

    sample_beancount = {sample!r}
    liability_community_property = "Community Prop"
    beancount_file = os.environ.get("BEANCOUNT_FILE", "").strip()
    if not beancount_file:
        sample_path = Path("/tmp/foresight_sample.beancount")
        sample_path.write_text(sample_beancount, encoding="utf-8")
        beancount_file = str(sample_path)
        beancount_error = ""
    elif not os.path.exists(beancount_file):
        beancount_error = f"File not found: `{{beancount_file}}`"
    else:
        beancount_error = ""'''
    if original not in source:
        raise ValueError("Could not find BEANCOUNT_FILE setup block in app.py")
    return source.replace(original, replacement, 1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a single-file Foresight artifact for molab.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file path. Defaults to {DEFAULT_OUTPUT.relative_to(ROOT)}.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output = build_artifact(args.output)
    print(output)


if __name__ == "__main__":
    main()
